#!/usr/bin/env bash
### dapp-build -- compile the source code
### Usage: dapp build
set -e

while [[ $# -gt 0 ]]; do
  opt=$1; shift
  case $opt in
    --legacy)
      DAPP_BUILD_LEGACY=1
      ;;
    *)
      echo >&2 "dapp-build: unknown argument: $opt"
      exit 1
      ;;
  esac
done

IFS=" " read -r -a opts <<<"$SOLC_FLAGS"
json_opts=--combined-json=abi,bin,bin-runtime,srcmap,srcmap-runtime,ast,metadata
solc --help | grep -q -- --overwrite && opts+=(--overwrite)

remappings=$(dapp remappings)
if [[ $remappings ]]; then
  while read -r line; do opts+=("$line"); done <<<"$remappings"
fi

if [ "$DAPP_LINK_TEST_LIBRARIES" = 1 ]; then
  DAPP_LINK_TEST_LIBRARIES=0 dapp build
  sender=0x00a329c0648769a73afac7f9381e08fb43dbea72
  nonce=1048576
  mapfile -t libraries < <(dapp --find-libraries)

  if [[ ${#libraries[@]} -eq 0 ]]; then exit; fi

  echo >&2 "${0##*/}: rebuilding with linked libraries"
  for lib in "${libraries[@]}"; do
    address=$(dapp address "$sender" "$nonce")
    links+=" $lib:$address"
    ((nonce++))
  done
  opts+=(--libraries "$links")
else
  (set -x; dapp clean)
fi

mkdir -p "$DAPP_OUT"
mapfile -t files < <(find "${DAPP_SRC}" -name '*.sol')
(set -x; solc "${opts[@]}" "${json_opts[@]}" /=/ "${files[@]}" > "${DAPP_JSON}")

if [ "$DAPP_BUILD_LEGACY" ]; then
  mapfile -t contracts < <(<"$DAPP_JSON" jq '.contracts|keys[]' -r | sort -u -t: -k2 | sort)
  data=$(<"$DAPP_JSON" jq '.contracts' -r)
  count=1
  total=${#contracts[@]}
  for path in "${contracts[@]}"; do
    echo -ne "[dapp] Extracting build data... [$count/$total]\\r"
    ((count++))
    name="${path#*:}"
    contract=$(echo "$data" | jq '.[''"'"$path"'"'']')
    echo "$contract" | jq '.["abi"]' -r > "$DAPP_OUT/$name.abi"
    echo "$contract" | jq '.["bin"]' -r > "$DAPP_OUT/$name.bin"
    echo "$contract" | jq '.["bin-runtime"]' -r > "$DAPP_OUT/$name.bin-runtime"
  done
  echo
  echo "[dapp] Stop using --legacy and extract your data from $DAPP_JSON for faster builds!"
fi
